import React, { useState, useEffect } from 'react';
import styled from 'styled-components';
import { MapPin, Clock, Mail, ArrowUpRight, Music, Users, Landmark, X, ChevronLeft, ChevronRight, Send, CheckCircle, Camera, BookOpen, GlassWater, Heart, CalendarDays } from 'lucide-react';
import { Container, Section, Eyebrow, Heading, Body, Button, PageHero, Reveal } from '../components/UI';
import { photos, activities, palette } from '../data/site';

const Split=styled.div`display:grid;grid-template-columns:1fr 1fr;gap:8%;align-items:center;@media(max-width:750px){grid-template-columns:1fr;gap:32px}img{width:100%;height:500px;object-fit:cover;@media(max-width:750px){height:320px}}`;
const Notice=styled.div`border-left:3px solid ${palette.gold};padding:18px 23px;background:#fff9f0;font-size:13px;line-height:1.8;color:#665a4d;margin:30px 0`;
const Paragraph=styled.p`font-size:15px;line-height:1.95;color:${p=>p.$light?'#d2c6b7':'#655b50'};max-width:680px`;
const PhotoGrid=styled.div`display:grid;grid-template-columns:repeat(3,1fr);gap:14px;@media(max-width:650px){grid-template-columns:repeat(2,1fr)}button{border:0;background:transparent;padding:0;overflow:hidden;cursor:zoom-in;position:relative}img{height:280px;width:100%;object-fit:cover;transition:transform .4s;&:hover{transform:scale(1.04)}@media(max-width:650px){height:190px}}span{position:absolute;bottom:0;left:0;right:0;padding:12px;background:#171411bd;color:white;text-align:left;font-size:12px}`;
const Overlay=styled.div`position:fixed;inset:0;z-index:100;background:#080706f5;display:flex;align-items:center;justify-content:center;padding:60px;@media(max-width:600px){padding:50px 15px}img{max-width:90vw;max-height:80vh;object-fit:contain}button{position:absolute;background:#ffffff18;color:white;border:1px solid #ffffff55;padding:12px;display:flex;align-items:center;justify-content:center}button.close{top:20px;right:20px}button.prev{left:20px}button.next{right:20px}`;

const galleryImages=[[photos.hero,'Bar og atmosfære'],[photos.interior,'Varme detaljer'],[photos.bar,'En plass ved baren'],[photos.social,'Møtestedet'],[photos.food,'Smak og stemning'],[photos.drink,'I glasset'],[photos.lounge,'En rolig krok'],[photos.table,'Rundt bordet']];
export function GalleryPage(){const[index,setIndex]=useState(null);useEffect(()=>{if(index===null)return;const key=e=>{if(e.key==='Escape')setIndex(null);if(e.key==='ArrowLeft')setIndex(v=>(v+galleryImages.length-1)%galleryImages.length);if(e.key==='ArrowRight')setIndex(v=>(v+1)%galleryImages.length)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[index]);return <><PageHero eyebrow="Bilder & stemning" title="Et glimt av Linna." description="En visuell reise gjennom atmosfære, detaljer og øyeblikk." image={photos.bar}/><Section><Container><Eyebrow>Galleri</Eyebrow><Heading>Atmosfære i hvert øyeblikk.</Heading><Paragraph>Det er detaljene som gjør et sted spesielt: lyset over bordene, teksturen i treverket og de små øyeblikkene mellom menneskene. Utforsk den visuelle retningen for Linna Pub nedenfor.</Paragraph><Notice>Bildene er illustrative stockbilder og viser ikke nødvendigvis Linna Pub. Erstatt dem med egne, godkjente fotografier før publisering.</Notice><PhotoGrid>{galleryImages.map(([src,title],i)=><button key={i} onClick={()=>setIndex(i)} aria-label={`Åpne bilde: ${title}`}><img src={src} alt={`Illustrasjonsfoto: ${title}`} loading="lazy"/><span>{title} ↗</span></button>)}</PhotoGrid></Container></Section><Section $alternate><Container><Split><Reveal><Eyebrow>Bak bildene</Eyebrow><Heading>Et uttrykk med varme og karakter.</Heading><Paragraph>En god bildeserie viser mer enn et rom. Den formidler hvordan det føles å være der. Derfor kombinerer denne demoen oversiktsbilder med detaljer, servering og sosiale øyeblikk.</Paragraph><Paragraph>Når ekte bilder er klare, kan galleriet deles inn i kategorier som interiør, mat og drikke, aktiviteter og mennesker.</Paragraph><Button to="/kontakt">Opplev stedet selv <ArrowUpRight size={16}/></Button></Reveal><img src={photos.interior} alt="Illustrasjonsfoto av et varmt interiør" loading="lazy"/></Split></Container></Section>{index!==null&&<Overlay role="dialog" aria-modal="true" aria-label="Bildevisning" onClick={()=>setIndex(null)}><button className="close" onClick={()=>setIndex(null)} aria-label="Lukk"><X/></button><button className="prev" onClick={e=>{e.stopPropagation();setIndex(v=>(v+galleryImages.length-1)%galleryImages.length)}} aria-label="Forrige"><ChevronLeft/></button><img onClick={e=>e.stopPropagation()} src={galleryImages[index][0]} alt={galleryImages[index][1]}/><button className="next" onClick={e=>{e.stopPropagation();setIndex(v=>(v+1)%galleryImages.length)}} aria-label="Neste"><ChevronRight/></button></Overlay>}</>}


